@startuml
'settings'
left to right direction

'actors'
actor "Non-customer" as nonuser
actor Customer as user
actor "Bank Staff" as staff

'databases'
database MySQL as mysql {
component customers
component accounts
component transactions
}



'bank system'
rectangle Bank {
    'account system'
    package Account {
        (Create account) as createAccount
        (Account management) as manageAccount
        (Freeze account) as freezeAccount
        (Close account) as closeAccount
        artifact account as acc
    }
    'transaction system'
    package Transactions {
        (Withdraw)
        (Deposit)
        (Transfer)
        (Review)
        artifact transaction as trans
    }
}
'signup usecase'
artifact customer
(Sign up as customer) as (signup)
nonuser -down-> (signup)
(signup) .. customer
customer -[dotted]--> customers

    'staff associations'
    staff -|> (Review)
    staff ---|> freezeAccount

    'user associations'
    user --> manageAccount
    user --> (Withdraw)
    user --> (Deposit)
    user --> (Transfer)
    user --> (Review)

    'transaction associations'
    (Withdraw) ..> trans : add
    (Deposit) ..> trans : add
    (Transfer) ..> trans : add
    (Review) <.. trans : get
    trans -[dotted]-> transactions

    'account associations'
    manageAccount --> createAccount
    manageAccount --> freezeAccount
    manageAccount --> closeAccount
    closeAccount -[dashed]-> acc : update
    freezeAccount -[dashed]-> acc : update
    createAccount -[dashed]-> acc : add
    acc -[dotted]-> accounts
@enduml